# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        cache: "yarn"
        registry-url: https://registry.npmjs.org/
    - run: yarn install --immutable
    - run: yarn build
    - name: yarn publish npm
      run: |
        yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
        yarn npm publish
    - uses: actions/setup-node@v5
      with:
        registry-url: https://npm.pkg.github.com/
    - name: set package name
      id: pkg_info
      run: |
        PKG_NAME="@${{ github.repository_owner }}/$(jq .name package.json | tr -d '\"')"
        echo "name=$PKG_NAME" >> $GITHUB_OUTPUT
    - name: yarn publish github
      run: |
        sed -i 's+"name": ".*+"name": "${{ steps.pkg_info.outputs.name }}",+gI' ./package.json
        yarn install
        yarn config set npmAuthToken ${{ secrets.GITHUB_TOKEN }}
        yarn npm publish
